const Sights = [

    // CATHEDRALS : 1-100
  {
    id: 1,
    block: "Соборы",
    title: "Исаакиевский собор",
    category: "Православные соборы",
    coords: [59.934137, 30.306233],
    // coords: {lat: 59.934137, lng: 30.306233},
    img: "../isaac.jpeg",
    link: "/isaac",
    url: "https://cathedral.ru/ru",
    price: "450",  
    address: "4 St Isaac's Square, St Petersburg",
    addressRus: "Исаакиевская пл., д. 4, 190000",
    workingTime: 
        `ПН: 10:30-18:00 ВТ: 10:30-18:00 СР: закрыто ЧТ: 10:30-18:00 ПТ: 10:30-18:00 СБ: 10:30-18:00 ВС: 10:30-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Вторник', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 2,
    block: "Соборы",
    title: "Казанский собор",
    category: "Православные соборы",
    coords: {lat: 59.934345, lng: 30.324611},
    img: "../kazan.jpeg",
    link: "/kazan",
    url: "http://kazansky-spb.ru/",
    price: "650",  
    address: "2 Kazan Square, St Petersburg",
    addressRus: "Казанская пл., д. 2, 191186",
    workingTime: 
        `ПН: 8:30-19:45 ВТ: 8:30-19:45 СР: 7-19:45 ЧТ: 7-19:45 ПТ: 7:30-19:45 СБ: 6:30-19:45 ВС: 6:30-19:45`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 3,
    block: "Соборы",
    title: "Спас-на-Крови",
    category: "Православные соборы",
    coords: [59.940070, 30.328633],
    // coords: {lat: 59.940070, lng: 30.328633},
    img: "../blood_savior.png",
    link: "/blood_savior",
    url: "http://spas.spb.ru/",
    price: "450",  
    address: "Griboyedov channel embankment, 2Б, St Petersburg",
    addressRus: "наб. канала Грибоедова, 2Б, 191186",
    workingTime: 
        `ПН: 10-18:00 ВТ: 10-18:00 СР: закрыто ЧТ: 10-18:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Вторник', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 4,
    block: "Соборы",
    title: "Смольный собор",
    category: "Православные соборы",
    coords: {lat: 59.948850, lng: 30.395467},
    img: "../smolniy.jpeg",
    link: "/smolniy",
    url: "http://smolnysobor.tilda.ws/",
    price: "300",  
    address: "Ploshchad' Rastrelli, 1, St Petersburg",
    addressRus: "пл. Растрелли, 1, 191124",
    workingTime: 
        `ПН: 8-20:00 ВТ: 8-20:00 СР: 8-20:00 ЧТ: 8-20:00 ПТ: 8-20:00 СБ: 8-20:00 ВС: 8-20:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 5,
    block: "Соборы",
    title: "Петропавловский собор",
    category: "Православные соборы",
    coords: {lat: 59.950117, lng: 30.316012},
    img: "../petropavlovskiy.jpeg",
    link: "/petropavlovskiy",
    url: "https://www.spbmuseum.ru/themuseum/museum_complex/peterpaul_fortress/",
    price: "550", 
    address: "Peter and Paul Fortress, St Petersburg, 197046",
    addressRus: "Петропавловская крепость, 197046",
    workingTime: 
        `ПН: 10-18:00 ВТ: 10-17:00 СР: закрыто ЧТ: 10-18:00 ПТ: 10-18:00 СБ: 10-17:45 ВС: 11-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Вторник', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 6,
    block: "Соборы",
    title: "Соборная мечеть",
    category: "Мусульманские мечети",
    coords: {lat: 59.955241, lng: 30.323908},
    img: "../sobornaya_mechet.jpeg",
    link: "/mechet",
    url: "https://dum-spb.ru/",
    price: "0",  
    address: "Kronverkskiy Prospekt, 7, St Petersburg",
    addressRus: "Кронверкский проспект, д. 7, 197046",
    workingTime: 
        `ПН: 10-17:00 ВТ: 10-17:00 СР: 10-17:00 ЧТ: 10-17:00 ПТ: 10-17:00 СБ: 10-17:00 ВС: 10-17:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 7,
    block: "Соборы",
    title: "Хоральная Синагога",
    category: "Синагоги",
    coords: {lat: 59.924707, lng: 30.291778},
    img: "../big-sinagoga.jpeg",
    link: "/big-sinagoga",
    url: "https://sinagoga.jeps.ru/",
    price: "500",  
    address: "Lermontovskiy Avenue, 2, 190121",
    addressRus: "Лермонтовский пр., д. 2, 190121",
    workingTime: 
        `ПН: 10-19:00 ВТ: 10-19:00 СР: 10-19:00 ЧТ: 10-19:00 ПТ: 10-15:00 СБ: закрыто ВС: 11-18:00`,
    noHolidays: "false", 
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 8,
    block: "Соборы",
    title: "Базилика Св. Екатерины",
    category: "Католические храмы",
    coords: {lat: 59.924707, lng: 30.291778},
    img: "../basilics.png",
    link: "/basilics",
    url: "https://catherine.spb.ru/",
    price: "0",  
    address: "Nevskiy Avenue, 32-34, 191186",
    addressRus: "Невский пр., д. 32-34, 191186",
    workingTime: 
        `ПН: 8-20:00 ВТ: 8-20:00 СР: 8-20:00 ЧТ: 8-20:00 ПТ: 8-20:00 СБ: 8-20:00 ВС: 8-20:00`,
    noHolidays: "true", 
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 9,
    block: "Соборы",
    title: "Церковь Св. Станислава",
    category: "Католические храмы",
    coords: {lat: 59.922678, lng: 30.288246},
    img: "../st-stanislaus.png",
    link: "/st-stanislaus",
    url: "https://stanislausspb.wordpress.com/",
    price: "0",  
    address: "Soyuza Pechatnikov Street, 22, 190121",
    addressRus: "ул. Союза Печатников, д. 22, 190121",
    workingTime: 
        `ПН: закрыто ВТ: закрыто СР: 17:30-21:00 ЧТ: 17:30-21:00 ПТ: 17:30-21:00 СБ: 17:30-21:00 ВС: 11-21:00`,
    noHolidays: "false", 
    days: ['Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 10,
    block: "Соборы",
    title: "Дацан Гунзэчойнэй",
    category: "Буддистские храмы",
    coords: {lat: 59.983492, lng: 30.256025},
    img: "../dazan.png",
    link: "/dazan",
    url: "https://dazanspb.ru/",
    price: "300",  
    address: "Primorskiy Avenue, 91",
    addressRus: "Приморский пр., д. 91",
    workingTime: 
        `ПН: 10-19:00 ВТ: 10-19:00 СР: закрыто ЧТ: 10-19:00 ПТ: 10-19:00 СБ: 10-19:00 ВС: 10-19:00`,
    noHolidays: "false", 
    days: ['Понедельник', 'Вторник', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },
  {
    id: 11,
    block: "Соборы",
    title: "Спасо-Преображенский",
    category: "Православные соборы",
    coords: {lat: 59.943022, lng: 30.352515},
    img: "../spaso-preobr.jpeg",
    link: "/spaso-preobr",
    url: "https://www.spaso-preobr-sobor.ru/",
    price: "0",  
    address: "Preobrazhenskaya Square, 1, 191028",
    addressRus: "Преображенская пл., д. 1, 191028",
    workingTime: 
        `ПН: 8-20:00 ВТ: 8-20:00 СР: 8-20:00 ЧТ: 8-20:00 ПТ: 8-20:00 СБ: 8-20:00 ВС: 8-20:00`,
    noHolidays: "true", 
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Билеты онлайн", "Вход для маломобильных граждан", "Метро рядом", "Аудиогид"], //
  },

  // BRIDGES : 101-200

//   {

//   }

  // MARKETS : 201-300

  {
    id: 201,
    block: "Рынки",
    title: "Василеостровский рынок",
    category: "Продуктовый",
    coords: {lat: 59.939385, lng: 30.285572},
    img: "../vasil_market.jpeg",
    link: "/vasil_market",
    url: "",
    address: "Bol'shoy Prospekt Vasil'yevskogo Ostrova, 16, St Petersburg, 199034",
    addressRus: "Большой проспект Васильевского острова, д. 16, 199034",
    workingTime: 
        `ПН: 8-22:00 ВТ: 8-22:00 СР: 8-22:00 ЧТ: 8-22:00 ПТ: 8-23:00 СБ: 8-23:00 ВС: 8-22:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
  },
  {
    id: 202,
    block: "Рынки",
    title: "Сенной рынок",
    category: "Продуктовый",
    coords: {lat: 59.924870, lng: 30.319139},
    img: "../sennoy_market.jpeg",
    link: "/sennoy_market",
    url: "",
    address: "Moskovskiy Prospekt, 4a, St Petersburg, 190031",
    addressRus: "Московский пр., 4а, 190031",
    workingTime: 
        `ПН: 8-20:00 ВТ: 8-20:00 СР: 8-20:00 ЧТ: 8-20:00 ПТ: 8-20:00 СБ: 8-20:00 ВС: 8-20:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
  },
  {
    id: 203,
    block: "Рынки",
    title: "Удельный рынок",
    category: "Блошиный",
    coords: {lat: 60.017774, lng: 30.312339},
    img: "../udelny_market.jpeg",
    link: "/udelny_market",
    url: "",
    address: "Fermskoye Shosse, 41 корпус 8, St Petersburg, 197341",
    addressRus: "Фермское шоссе, 41 корпус 8, 197341",
    workingTime: 
        `ПН: 10-20:00 ВТ: 10-20:00 СР: 10-20:00 ЧТ: 10-20:00 ПТ: 10-20:00 СБ: 7-19:00 ВС: 7-19:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
  },
  {
    id: 204,
    block: "Рынки",
    title: "Апраксин Двор",
    category: "Вещевой",
    coords: {lat: 59.929262, lng: 30.328305},
    img: "../apraksin_dvor.jpeg",
    link: "/apraksin_dvor",
    url: "",
    address: "Апраксин двор, St Petersburg, 191023",
    addressRus: "Апраксин двор, 191023",
    workingTime: 
        `ПН: 7:30-18:00 ВТ: 7:30-18:00 СР: 7:30-18:00 ЧТ: 7:30-18:00 ПТ: 7:30-18:00 СБ: 7:30-18:00 ВС: 7:30-18:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
  },
  {
    id: 205,
    block: "Рынки",
    title: "Сытный рынок",
    category: "Продуктовый",
    coords: {lat: 59.956971, lng: 30.309317},
    img: "../sytny_market.png",
    link: "/sytniy_market",
    url: "",
    address: "Sytninskaya Square, 5A, St Petersburg, 197101",
    addressRus: "Сытнинская пл., 5А, 197101",
    workingTime: 
        `ПН: 10-19:00 ВТ: 10-19:00 СР: 10-19:00 ЧТ: 10-19:00 ПТ: 10-19:00 СБ: 10-19:00 ВС: закрыто`,
    noHolidays: "false",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
  },
  {
    id: 206,
    block: "Рынки",
    title: "Мальцевский рынок",
    category: "Продуктовый",
    coords: {lat: 59.938705, lng: 30.366090},
    img: "../malcevsky_market.jpeg",
    link: "/malcevsky_market",
    url: "",
    address: "Ulitsa Nekrasova, 52, St Petersbur, 191014",
    addressRus: "ул. Некрасова, д. 52, 191014",
    workingTime: 
        `ПН: 9-20:00 ВТ: 9-20:00 СР: 9-20:00 ЧТ: 9-20:00 ПТ: 9-20:00 СБ: 9-20:00 ВС: 9-19:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
  },

  // MONUMENTS : 301-400

  {
    id: 301,
    block: "Памятники",
    title: "Медный Всадник",
    category: "",
    coords: {lat: 59.936383, lng: 30.302243}, 
    img: "../horseman.jpeg",
    link: "/horseman",
    address: "",
    addressRus: "",
  },
  {
    id: 302,
    block: "Памятники",
    title: "Царь-Плотник",
    category: "",
    coords: {lat: 59.939227, lng: 30.307584}, 
    img: "../tsar-carpenter.jpeg",
    link: "/tsar-carpenter",
    address: "",
    addressRus: "",
  },
  {
    id: 303,
    block: "Памятники",
    title: "Памятник Екатерине II",
    category: "",
    coords: {lat: 59.933346, lng: 30.336970}, 
    img: "../catherine.jpeg",
    link: "/catherine",
    address: "",
    addressRus: "",
  },
  {
    id: 304,
    block: "Памятники",
    title: "Ростральные колонны",
    category: "",
    coords: {lat: 59.944660, lng: 30.304997}, 
    img: "../rostral-columns.jpeg",
    link: "/rostral-columns",
    address: "",
    addressRus: "",
  },
  {
    id: 305,
    block: "Памятники",
    title: "Памятник Николаю I",
    category: "",
    coords: {lat: 59.932105, lng: 30.308427}, 
    img: "../nikolay-first.jpeg",
    link: "/nikolay-first",
    address: "",
    addressRus: "",
  },
  {
    id: 306,
    block: "Памятники",
    title: "Чижик-Пыжик",
    category: "",
    coords: {lat: 59.941710, lng: 30.338017}, 
    img: "../chizhik.jpeg",
    link: "/chizhik",
    address: "",
    addressRus: "",
  },

  // LIBRARIES : 401-500

//   {

//   },

  // PARKS : 501-600

  {
    id: 501,
    block: "Парки",
    title: "Летний сад",
    category: "history",
    coords: {lat: 59.947112, lng: 30.333932},
    img: "../summer_garden.jpeg",
    link: "/summer_garden",
    address: "Naberezhnaya Leb'yazh'yey Kanavki, 3, St Petersburg",
    addressRus: "наб. Лебяжьей канавки, 3, 191186",
    workingTime: 
        `ПН: 10-22:00 ВТ: закрыто СР: 10-22:00 ЧТ: 10-22:00 ПТ: 10-22:00 СБ: 10-22:00 ВС: 10-22:00`,
    price: "0",
    noHolidays: "false",
    days: ['Понедельник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    rent: [""],
    activities: ['Лавочки'],
    others: ["Оплата картой", "Вход для маломобильных граждан"], //
  },
  {
    id: 502,
    block: "Парки",
    title: "Марсово поле",
    category: "history",
    coords: [59.943553, 30.331705],
    // coords: {lat: 59.943553, lng: 30.331705},
    img: "../marsovo_field.jpeg",
    link: "/marsovo_field",
    url: "",
    address: "Naberezhnaya Leb'yazh'yey Kanavki, 3, St Petersburg",
    addressRus: "наб. Лебяжьей канавки, 3, 191186",
    workingTime: 
        `ПН: 9-17:00 ВТ: 9-17:00 СР: 9-17:00 ЧТ: 9-17:00 ПТ: 9-17:00 СБ: закрыто ВС: закрыто`,
    price: "0",
    noHolidays: "false",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница'],
    rent: [""],
    activities: ['Лавочки'],
    others: ["Вход для маломобильных граждан"], //
  },
  {
    id: 503,
    block: "Парки",
    title: "Александровский сад",
    category: "history",
    coords: {lat: 59.936309, lng: 30.306930},
    img: "../alexander_garden.png",
    link: "/alexander_garden",
    url: "",
    address: "Garden Aleksandrovskiy, St Petersburg",
    addressRus: "Александровский сад, 197101",
    workingTime: 
        `ПН: весь день ВТ: весь день СР: весь день ЧТ: весь день ПТ: весь день СБ: весь день ВС: весь день`,
    price: "0",
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    rent: [""],
    activities: ['Лавочки'],
    others: ["Вход для маломобильных граждан"], //
  },
  {
    id: 504,
    block: "Парки",
    title: "Парк 300-летия",
    category: "activity",
    coords: {lat: 59.984085, lng: 30.202163},
    img: "../park_300_years.jpeg",
    link: "/park_three",
    url: "",
    address: "Primorskiy Prospekt, 74, St Petersburg",
    addressRus: "Приморский проспект, 74, 197374",
    workingTime: 
        `ПН: 7-23:00 ВТ: 7-23:00 СР: 7-23:00 ЧТ: 7-23:00 ПТ: 7-23:00 СБ: 7-23:00 ВС: 7-23:00`,
    price: "0",
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    rent: ["Велосипеды", "Самокаты", "Роликовые коньки"],
    activities: ['Детские площадки', 'Зона для пикников', 'Лавочки', 'Кофейни', 'Рестораны и кафе'],
    others: ["Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 505,
    block: "Парки",
    title: "Елагин парк",
    category: "activity",
    coords: {lat: 59.979264, lng: 30.258742},
    img: "../park_culture.jpeg",
    link: "/park_culture",
    url: "",
    address: "Елагин остров, 4, лит.Б, St Petersburg, 197110",
    addressRus: "Елагин остров, д. 4, лит. Б, 197110",
    workingTime: 
        `ПН: 6-22:00 ВТ: 6-22:00 СР: 6-22:00 ЧТ: 6-22:00 ПТ: 6-22:00 СБ: 6-22:00 ВС: 6-22:00`,
    price: "100",
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    rent: ["Велосипеды", "Роликовые коньки", 'Лодки', 'Лыжи', 'Сани'],
    activities: ['Детские площадки', 'Каток', 'Спортивные площадки', 'Зона для пикников', 'Лавочки', 'Кофейни', 'Рестораны и кафе'],
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 506,
    block: "Парки",
    title: "Михайловский сад",
    category: "history",
    coords: {lat: 59.939846, lng: 30.332822},
    img: "../mikhail_garden.jpeg",
    link: "/mikhail_garden",
    url: "",
    address: "St Petersburg, 191186",
    addressRus: "Санкт-Петербург, 191186",
    workingTime: 
        `ПН: 10-22:00 ВТ: 10-22:00 СР: 10-22:00 ЧТ: 10-22:00 ПТ: 10-22:00 СБ: 10-22:00 ВС: 10-22:00`,
    price: "0",
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    rent: [""],
    activities: ['Детские площадки', 'Лавочки', 'Кофейни', 'Рестораны и кафе'],
    others: ["Вход для маломобильных граждан"], //
  },

    // SQUARES : 601-700

  {
    id: 601,
    block: "Площади",
    title: "Дворцовая площадь",
    category: "",
    coords: [59.938991, 30.315473],
    // coords: {lat: 59.938991, lng: 30.315473},
    img: "../palace-square.jpeg",
    link: "/palace-square",
    address: "",
    addressRus: "",
  },
  {
    id: 602,
    block: "Площади",
    title: "Исаакиевская площадь",
    category: "",
    coords: {lat: 59.932644, lng: 30.307927},
    img: "../isaac-square.png",
    link: "/isaac-square",
    address: "",
    addressRus: "",
  },
  {
    id: 603,
    block: "Площади",
    title: "Сенатская площадь",
    category: "",
    coords: {lat: 59.936458, lng: 30.302295},
    img: "../senate-square.jpeg",
    link: "/senate-square",
    address: "",
    addressRus: "",
  },
  {
    id: 604,
    block: "Площади",
    title: "Площадь Искусств",
    category: "",
    coords: {lat: 59.937445, lng: 30.331723},
    img: "../art-square.jpeg",
    link: "/art-square",
    address: "",
    addressRus: "",
  },
  {
    id: 605,
    block: "Площади",
    title: "Казанская площадь",
    category: "",
    coords: {lat: 59.935002, lng: 30.325202},
    img: "../kazan-square.jpeg",
    link: "/kazan-square", 
    address: "",
    addressRus: "",
  },
  {
    id: 606,
    block: "Площади",
    title: "Манежная площадь",
    category: "",
    coords: {lat: 59.935913, lng: 30.340347},
    img: "../manezh-square.jpeg",
    link: "/manezh-square",
    address: "",
    addressRus: "",
  },

  // THEATRES : 701-800

  {
    id: 701,
    block: "Театры",
    title: "Мариинский театр",
    category: "Опера и балет",
    coords: {lat: 59.925719, lng: 30.296367},
    img: "../mariin_theatre_old.jpeg",
    link: "/mariin_old",
    url: "",
    address: "Theatre Square, 1, St Petersburg, 190000",
    addressRus: "Театральная пл., 1, 190000",
    price: "",
  },
  {
    id: 702,
    block: "Театры",
    title: "Мариинский-2",
    category: "Опера и балет",
    coords: {lat: 59.925258, lng: 30.294180},
    img: "../mariin_theatre_new.jpeg",
    link: "/mariin_new",
    url: "",
    address: "Ulitsa Dekabristov, 34, St Petersburg, 190000",
    addressRus: "ул. Декабристов, д. 34, 190000",
    price: "",
  },
  {
    id: 703,
    block: "Театры",
    title: "Концертный зал",
    category: "Концертные залы",
    coords: {lat: 59.925236, lng: 30.287374},
    img: "../mariin_theatre_concert.jpeg",
    link: "/mariin_concert",
    url: "",
    address: "Ulitsa Pisareva, 20, St Petersburg, 190121",
    addressRus: "ул. Писарева, д.20, 190121",
    price: "",
  },
  {
    id: 704,
    block: "Театры",
    title: "БДТ",
    category: "Драматические театры",
    coords: {lat: 59.927394, lng: 30.331054},
    img: "../big_drama_theatre.jpeg",
    link: "/big_drama",
    url: "",
    address: "Fontanka River Embankment, 65, St Petersburg, 190031",
    addressRus: "наб. Фонтанки, д. 65, 190031",
    price: "",
  },
  {
    id: 705,
    block: "Театры",
    title: "Александринский театр",
    category: "Опера и балет",
    coords: {lat: 59.931793, lng: 30.336300},
    img: "../aleksandrin_theatre.jpeg",
    link: "/alexandrin_theatre",
    url: "",
    address: "Ostrovskogo Square, 6, St Petersburg, 191011",
    addressRus: "пл. Островского, д. 6, 191011",
    price: "",
  },
  {
    id: 706,
    block: "Театры",
    title: "Большой Театр Кукол",
    category: "Детские театры",
    coords: {lat: 59.939104, lng: 30.352018},
    img: "../dolls_theatre.jpeg",
    link: "/dolls_theatre",
    url: "",
    address: "Ulitsa Nekrasova, 10, St Petersburg, 191014",
    addressRus: "ул. Некрасова, 10, 191014",
    price: "",
  },
  {
    id: 707,
    block: "Театры",
    title: "ТЮЗ",
    category: "Детские театры",
    coords: {lat: 59.919915, lng: 30.334830},
    img: "../tyuz.png",
    link: "/tyuz",
    url: "https://www.tyuz-spb.ru",
    address: "Pionerskaya ploshchad, 1, 191119",
    addressRus: "Пионерская пл., д. 1, 191119",
    price: "",
  },
  {
    id: 708,
    block: "Театры",
    title: "Театр Буфф",
    category: "Театры комедии",
    coords: {lat: 59.931567, lng: 30.417352},
    img: "../buff.png",
    link: "/buff",
    url: "https://buffspb.ru",
    address: "пр. Шаумяна, 22, 195112",
    addressRus: "пр. Шаумяна, д. 22, 195112",
    price: "",
  },
  {
    id: 709,
    block: "Театры",
    title: "Театр им. Ленсовета",
    category: "Драматические театры",
    coords: {lat: 59.930219, lng: 30.348263},
    img: "../lensov-theatre.png",
    link: "/lensov-theatre",
    url: "https://lensov-theatre.spb.ru/buy/",
    address: "Vladimirskiy Avenue, 12, 191025",
    addressRus: "Владимирский пр., д. 12, 191025",
    price: "",
  },
  {
    id: 710,
    block: "Театры",
    title: "Мюзик Холл",
    category: "Концертные залы",
    coords: {lat: 59.955074, lng: 30.310522},
    img: "../music-hall.png",
    link: "/music-hall",
    url: "https://chaliapin-teatr.ru",
    address: "4M, Aleksandrovskiy Park",
    addressRus: "Александровский парк, 4М",
    price: "",
  },
  {
    id: 711,
    block: "Театры",
    title: "Приют Комедианта",
    category: "Театры комедии",
    coords: {lat: 59.929111, lng: 30.323021},
    img: "../priyut-comedy.png",
    link: "/priyut-comedy",
    url: "https://pkteatr.ru",
    address: "Sadovaya Street, 27",
    addressRus: "Садовая ул., д. 27",
    price: "",
  },
  {
    id: 712,
    block: "Театры",
    title: "Городской театр",
    category: "Камерные театры",
    coords: {lat: 59.937772, lng: 30.350086},
    img: "../city-theatre.png",
    link: "/city-theatre",
    url: "https://goteatr.ru",
    address: "Liteyniy Avenue, 46, 191014",
    addressRus: "Литейный пр., д. 46, 191014",
    price: "",
  },

    // MUSEUMS : 801-1000

  {
    id: 801,
    block: "Музеи",
    title: "Эрмитаж",
    category: "Искусство",
    coords: {lat: 59.939864, lng: 30.314566},
    img: "../hermitage.jpeg",
    link: "/hermitage",
    url: "https://www.hermitagemuseum.org/wps/portal/hermitage/",
    price: "500", 
    address: "2 Palace Square, St Petersburg",
    addressRus: "Дворцовая пл., д. 2, 190000",
    workingTime: 
        `ПН: закрыто ВТ: 11-20:00 СР: 11-18:00 ЧТ: 11-18:00 ПТ: 11-20:00 СБ: 11-20:00 ВС: 11-18:00`,
    noHolidays: "false",
    days: ['Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'], 
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 802,
    block: "Музеи",
    title: "Эрарта",
    category: "Искусство",
    coords: {lat: 59.932206, lng: 30.251440},
    img: "../erarta.jpeg",
    link: "/erarta",
    url: "https://www.erarta.com/",
    price: "1000", 
    address: "29 Liniya Vasil'yevskogo Ostrova, 2, St Petersburg",
    addressRus: "29 лин. Васильевского острова, д. 2, 199106",
    workingTime: 
        `ПН: 11-23:00 ВТ: закрыто СР: 11-23:00 ЧТ: 11-23:00 ПТ: 11-23:00 СБ: 11-23:00 ВС: 11-23:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "true", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "false",
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 803,
    block: "Музеи",
    title: "Кунсткамера",
    category: "Естественные науки",
    coords: [59.941545, 30.304488],
    // coords: {lat: 59.941545, lng: 30.304488},
    img: "../kunstkamera.jpeg",
    link: "/kunstkamera",
    url: "https://www.kunstkamera.ru/",
    price: "400", 
    address: "University Embankment, 3, St Petersburg",
    addressRus: "Университетская наб., д. 3, 199034",
    workingTime: 
        `ПН: закрыто ВТ: 10-18:00 СР: 10-18:00 ЧТ: 10-18:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true",
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 804,
    block: "Музеи",
    title: "Гранд Макет",
    category: "Для детей",
    coords: {lat: 59.888076, lng: 30.330452},
    img: "../grand_maket.jpeg",
    link: "/grand_maket",
    url: "https://grandmaket.ru/",
    price: "860", 
    address: "Tsvetochnaya Ulitsa, 16, St Petersburg",
    addressRus: "Цветочная ул., д. 16, 196084",
    workingTime: 
        `ПН: 10-20:00 ВТ: 10-20:00 СР: 10-20:00 ЧТ: 10-20:00 ПТ: 10-20:00 СБ: 10-20:00 ВС: 10-20:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "true", //
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 805,
    block: "Музеи",
    title: "Крейсер Аврора",
    category: "Военные музеи",
    coords: {lat: 59.955490, lng: 30.337842},
    img: "../creiser.jpeg",
    link: "/creiser",
    url: "https://kreyser-avrora.ru",
    price: "550",  
    address: "Petrogradskaya Embankment, St Petersburg, 197046",
    addressRus: "Петроградская наб., 197046",
    workingTime: 
        `ПН: закрыто ВТ: закрыто СР: 11-18:00 ЧТ: 11-18:00 ПТ: 11-18:00 СБ: 11-18:00 ВС: 11-18:00`,
    noHolidays: "false",
    days: ['Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 806,
    block: "Музеи",
    title: "Русский музей",
    category: "Искусство",
    coords: {lat: 59.938782, lng: 30.332383},
    img: "../russian_museum.jpeg",
    link: "/russian_museum",
    url: "https://ticket.rusmuseum.ru/?id=12&sid=523",
    price: "600",  
    address: "Inzhenernaya St, 4, St Petersburg",
    addressRus: "Инженерная ул., д. 4, 191186",
    workingTime: 
        `ПН: 10-18:00 ВТ: закрыто СР: 10-18:00 ЧТ: 13-21:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", //
    forDisabled: "true", 
    byCard: "true", 
    metro: "true", 
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 807,
    block: "Музеи",
    title: "Арка Главного штаба",
    category: "Искусство",
    coords: {lat: 59.938790, lng: 30.317904},
    img: "../glav-shtab.jpeg",
    link: "/glav-shtab",
    url: "https://hermitagemuseum.org/wps/portal/hermitage/",
    price: "1000",  
    address: "Palace Square, St Petersburg, 191186",
    addressRus: "Дворцовая пл., 191186",
    workingTime: //
        `ПН: 10-18:00 ВТ: закрыто СР: 10-18:00 ЧТ: 13-21:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 808,
    block: "Музеи",
    title: "Петропавловская крепость",
    category: "Военные музеи",
    coords: {lat: 59.950258, lng: 30.315635},
    img: "../petropav-krepost.jpeg",
    link: "/petropav-krepost",
    url: "",
    price: "0", 
    address: "St Petersburg, 197046",
    addressRus: "197046",
    workingTime: 
        `ПН: 10-16:00 ВТ: 10-16:00 СР: закрыто ЧТ: 10-16:00 ПТ: 10-16:00 СБ: 10-16:00 ВС: 10-16:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Вторник', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", //
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true",
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 809,
    block: "Музеи",
    title: "Музей артиллерии",
    category: "Военные музеи",
    coords: {lat: 59.954054, lng: 30.313727},
    img: "../museum-artillerii.jpeg",
    link: "/museum-artillerii",
    url: "https://www.artillery-museum.ru/",
    price: "500", 
    address: "Park Aleksandrovskiy, 7, St Petersburg, 197101",
    addressRus: "парк Александровский, 7, 197101",
    workingTime: 
        `ПН: закрыто ВТ: закрыто СР: 11-18:00 ЧТ: 11-18:00 ПТ: 11-18:00 СБ: 11-18:00 ВС: 11-18:00`,
    noHolidays: "false",
    days: ['Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", 
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 810,
    block: "Музеи",
    title: "Музей Титикака",
    category: "Музеи рекордов",
    coords: {lat: 59.932366, lng: 30.321472},
    img: "../titikaka-museum.jpeg",
    link: "/titikaka-museum",
    url: "https://titiqaqa.ru/",
    price: "700",  
    address: "Kazanskaya St, 7, St Petersburg, 191186",
    addressRus: "Казанская ул., д.7, 191186",
    workingTime: 
        `ПН: 10-21:00 ВТ: 10-21:00 СР: 10-21:00 ЧТ: 10-21:00 ПТ: 10-21:00 СБ: 10-21:00 ВС: 10-21:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", //
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Пенсионеры", "Дошкольники"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 811,
    block: "Музеи",
    title: "Музей Арктики",
    category: "Естественные науки",
    coords: {lat: 59.927425, lng: 30.353507},
    img: "../museum-arctic.jpeg",
    link: "/museum-arctic",
    url: "https://polarmuseum.ru/",
    price: "350",  
    address: "Ul Marata, 24A, St Petersburg, 191040",
    addressRus: "ул. Марата, 24А, 191040",
    workingTime: 
        `ПН: закрыто ВТ: закрыто СР: 10-18:00 ЧТ: 10-18:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 812,
    block: "Музеи",
    title: "Вселенная воды",
    category: "Естественные науки",
    coords: {lat: 59.949532, lng: 30.376098},
    img: "../water-universe.jpeg",
    link: "/water-universe",
    url: "https://www.vodokanal-museum.ru/booking2/",
    price: "540",  
    address: "Shpalernaya Ulitsa, 56, St Petersbug, 191015",
    addressRus: "Шпалерная ул., д.56, 191015",
    workingTime: 
        `ПН: закрыто ВТ: закрыто СР: 10-18:00 ЧТ: 10-18:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "true", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 813,
    block: "Музеи",
    title: "Юсуповский дворец",
    category: "Дворцы",
    coords: {lat: 59.929384, lng: 30.298870},
    img: "../yusupov-palace.jpeg",
    link: "/yusupov-palace",
    url: "https://yusupov-palace.ru/ru",
    price: "500",  
    address: "Ulitsa Dekabristov, 21, St Petersburg, 190000",
    addressRus: "ул. Декабристов, д. 21, 190000",
    workingTime: 
        `ПН: 10-19:30 ВТ: 10-19:30 СР: 10-19:30 ЧТ: 10-19:30 ПТ: 10-19:30 СБ: 10-19:30 ВС: 10-19:30`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 814,
    block: "Музеи",
    title: "Этнографический музей",
    category: "Этнография",
    coords: {lat: 59.937882, lng: 30.334382},
    img: "../etnography.jpeg",
    link: "/etnography-museum",
    url: "https://ethnomuseum.ru/",
    price: "400",  
    address: "Inzhenernaya St, 4/1, St Petersburg, 191011",
    addressRus: "Инженерная ул., 4/1, 191011",
    workingTime: 
        `ПН: закрыто ВТ: 10-21:00 СР: 10-18:00 ЧТ: 10-18:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 815,
    block: "Музеи",
    title: "Мраморный дворец",
    category: "Дворцы",
    coords: {lat: 59.945188, lng: 30.326946},
    img: "../marble-palace.jpeg",
    link: "/marble-palace",
    url: "https://rusmuseum.ru/marble-palace/exhibitions/",
    price: "500",  
    address: "Millionnaya St, 5/1, St Petersburg, 191186",
    addressRus: "Миллионная ул., 5/1, 191186",
    workingTime: 
        `ПН: 10-18:00 ВТ: закрыто СР: 10-18:00 ЧТ: 13-21:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", 
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 816,
    block: "Музеи",
    title: "Дворец Меншикова",
    category: "Дворцы",
    coords: {lat: 59.938767, lng: 30.295782},
    img: "../menshikov-palace.jpeg",
    link: "/menshikov-palace",
    url: "https://hermitagemuseum.org/wps/portal/hermitage/visitus/menshikov-palace/?lng=ru",
    price: "600",  
    address: "University Embankment, 15, St Petersburg, 190000",
    addressRus: "Университетская наб., 15, 190000",
    workingTime: 
        `ПН: закрыто ВТ: 10:30-17:00 СР: 10:30-20:00 ЧТ: 10:30-17:00 ПТ: 10:30-20:00 СБ: 10:30-17:00 ВС: 10:30-17:00`,
    noHolidays: "false",
    days: ['Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", //
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 817,
    block: "Музеи",
    title: "Музей теней",
    category: "Физика",
    coords: {lat: 59.940510, lng: 30.323540},
    img: "../shadows-museum.webp",
    link: "/shadows-museum",
    url: "https://shadowmuseum.ru/",
    price: "450",  
    address: "Bolshaya Konyushennaya St, 5A, St Petersburg, 191186",
    addressRus: "Большая Конюшенная ул., 5А, 191186",
    workingTime: 
        `ПН: 11-22:00 ВТ: 11-22:00 СР: 11-22:00 ЧТ: 11-22:00 ПТ: 11-22:00 СБ: 11-22:00 ВС: 11-22:00`,
    noHolidays: "true",
    days: ['Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "false", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Бесплатная парковка", "Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 818,
    block: "Музеи",
    title: "Михайловский замок",
    category: "Замки",
    coords: [59.940735, 30.337600],
    // coords: {lat: 59.940735, lng: 30.337600},
    img: "../mikhail-castle.jpeg",
    link: "/mikhail-castle",
    url: "https://rusmuseum.ru/",
    price: "550",  
    address: "Sadovaya St, 2, St Petersburg, 191023",
    addressRus: "Садовая ул., 2, 191023",
    workingTime: 
        `ПН: 10-18:00 ВТ: закрыто СР: 10-18:00 ЧТ: 13-21:00 ПТ: 10-18:00 СБ: 10-18:00 ВС: 10-18:00`,
    noHolidays: "false",
    days: ['Понедельник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", //
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 819,
    block: "Музеи",
    title: "Музей Ф.М. Достоевского",
    category: "Мемориальные квартиры",
    coords: {lat: 59.927376, lng: 30.350695},
    img: "../museum-dostoevsky.jpeg",
    link: "/museum-dostoevsky",
    url: "https://md.spb.ru/",
    price: "300",  
    address: "Kuznechnyy Pereulok, 5/2, St Petersburg, 191002",
    addressRus: "Кузнечный пер., 5/2, 191002",
    workingTime: 
        `ПН: закрыто ВТ: 11-18:00 СР: 13-20:00 ЧТ: 11-18:00 ПТ: 11-18:00 СБ: 11-18:00 ВС: 11-18:00`,
    noHolidays: "false",
    days: ['Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
  },
  {
    id: 820,
    block: "Музеи",
    title: "Квартира А.С. Пушкина",
    category: "Мемориальные квартиры",
    coords: {lat: 59.941145, lng: 30.321111},
    img: "../museum-pushkin.jpeg",
    link: "/museum-pushkin",
    url: "http://www.museumpushkin.ru/",
    price: "800",  
    address: "embankment Riv Moyka, 12, St Petersburg, 191186",
    addressRus: "наб. реки Мойки, д.12, 191186",
    workingTime: 
        `ПН: закрыто ВТ: 10:30-18:00 СР: 10:30-18:00 ЧТ: 10:30-18:00 ПТ: 10:30-18:00 СБ: 10:30-18:00 ВС: 10:30-18:00`,
    noHolidays: "false",
    days: ['Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота', 'Воскресенье'],
    parking: "false", 
    forDisabled: "true", //
    byCard: "true", 
    metro: "true", 
    audioGuide: "true", 
    others: ["Оплата картой", "Вход для маломобильных граждан", "Бесплатное Wi-Fi подключение"], //
    privileges: ["Студенты", "Пенсионеры", "Дошкольники", "Ветераны"], //
  },
];


export default Sights;